# Generated by Django 2.2.3 on 2019-08-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_Favo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.comment')),
                ('nameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.users')),
            ],
        ),
    ]
