# Generated by Django 2.2.3 on 2019-08-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_comm_favo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm_favo',
            name='isFavorite',
            field=models.IntegerField(default=0),
        ),
    ]
